# Generated by Django 5.0.4 on 2024-04-26 22:16

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ends_in',
            field=models.DateField(validators=[subscriptions.models.validate_future_date]),
        ),
    ]
