# Generated by Django 5.0.4 on 2024-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Academic Goal',
                'verbose_name_plural': 'Academic Goals',
            },
        ),
        migrations.CreateModel(
            name='Cirriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirriculum', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Cirriculum',
                'verbose_name_plural': 'Cirriculums',
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Class Time',
                'verbose_name_plural': 'Class Times',
            },
        ),
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Class Year',
                'verbose_name_plural': 'Class Years',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
            },
        ),
        migrations.CreateModel(
            name='StudentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Student Count',
                'verbose_name_plural': 'Student Counts',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='SuitableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=128)),
            ],
            options={
                'verbose_name': 'Suitable Day',
                'verbose_name_plural': 'Suitable Days',
            },
        ),
        migrations.CreateModel(
            name='SuitableDayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Morning time', 'Morning time'), ('Evening time', 'Evening time')], max_length=128)),
            ],
            options={
                'verbose_name': 'Suitable Day Period',
                'verbose_name_plural': 'Suitable Day Periods',
            },
        ),
        migrations.CreateModel(
            name='SuitableDayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Suitable Day Time',
                'verbose_name_plural': 'Suitable Day Times',
            },
        ),
        migrations.CreateModel(
            name='WeeklyClassCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Weekly Class',
                'verbose_name_plural': 'Weekly Classes',
            },
        ),
    ]
