# Generated by Django 5.0.4 on 2024-04-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_classtime_class_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcount',
            name='student_count',
            field=models.CharField(max_length=128),
        ),
    ]
