# Generated by Django 5.0.4 on 2024-04-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_studentcount_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='subjects'),
        ),
    ]
