# Generated by Django 5.0.4 on 2024-04-25 16:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('education', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[(users.models.GenderChoices['MALE'], 'Male'), (users.models.GenderChoices['FEMALE'], 'Female')], max_length=5)),
                ('nationality', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=15)),
                ('difficulties', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('academic_goals', models.ManyToManyField(to='education.academicgoal')),
                ('cirriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.cirriculum')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.classtime')),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.classyear')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.educationlevel')),
                ('student_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.studentcount')),
                ('subjects', models.ManyToManyField(to='education.subject')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
                ('suitable_day_periods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.suitabledayperiod')),
                ('suitable_day_times', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.suitabledaytime')),
                ('suitable_days', models.ManyToManyField(to='education.suitableday')),
                ('weekly_class_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.weeklyclasscount')),
            ],
        ),
    ]
