# Generated by Django 5.0.4 on 2024-04-26 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscriber_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='whatsapp',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Phone number may or may not start with "+". Minimum length of 14 numbers. Max length of 18 numbers. Only numbers and "+" are allowed.', regex='^(\\+?\\d{10,18})$')]),
        ),
    ]
